import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import AppHeader from './components/app.header';
import AppFooter from './components/app.footer';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Hospital 103',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppHeader/>
        <div className='container-fluid'>
          {children}
        </div>     
        <AppFooter/>   
      </body>
    </html>
  )
}
